-- Auth.js (@auth/supabase-adapter) 전용 스키마
-- Supabase SQL Editor에서 실행하세요. (schema.sql보다 먼저 실행)
--
-- 접근 전략: service_role만 허용, anon/authenticated는 이중으로 차단
--   1) 스키마 usage 권한 자체를 부여하지 않음
--   2) 각 테이블에 RLS 활성화 + 정책 없음 = 모든 JWT 접근 거부
--   service_role은 RLS를 우회하므로 영향 없음.

create schema if not exists next_auth;

-- anon, authenticated 역할에 스키마 접근 권한을 명시적으로 부여하지 않음
-- (Supabase 기본값으로 새 스키마는 public 역할에만 접근 가능하나 명시적으로 차단)
revoke usage on schema next_auth from anon, authenticated;

grant usage on schema next_auth to service_role;
-- 테이블 생성 전에 실행되면 기존 테이블에만 적용됨 → 생성 후 재실행 또는 아래 DEFAULT PRIVILEGES로 보완
grant all privileges on all tables in schema next_auth to service_role;
grant all privileges on all sequences in schema next_auth to service_role;
grant all privileges on all routines in schema next_auth to service_role;

-- 앞으로 새 테이블/시퀀스가 추가되면 자동으로 service_role에 권한 부여
alter default privileges in schema next_auth
  grant all privileges on tables to service_role;
alter default privileges in schema next_auth
  grant all privileges on sequences to service_role;

create table if not exists next_auth.users (
  id            uuid not null default gen_random_uuid(),
  name          text,
  email         text,
  "emailVerified" timestamptz,
  image         text,
  primary key (id)
);

alter table next_auth.users enable row level security;
create unique index if not exists next_auth_users_email_idx on next_auth.users (email);

create table if not exists next_auth.accounts (
  id                   uuid not null default gen_random_uuid(),
  "userId"             uuid not null references next_auth.users(id) on delete cascade,
  type                 text not null,
  provider             text not null,
  "providerAccountId"  text not null,
  refresh_token        text,
  access_token         text,
  expires_at           bigint,
  token_type           text,
  scope                text,
  id_token             text,
  session_state        text,
  oauth_token_secret   text,
  oauth_token          text,
  primary key (id)
);

alter table next_auth.accounts enable row level security;

create table if not exists next_auth.sessions (
  id             uuid not null default gen_random_uuid(),
  expires        timestamptz not null,
  "sessionToken" text not null,
  "userId"       uuid not null references next_auth.users(id) on delete cascade,
  primary key (id)
);

alter table next_auth.sessions enable row level security;
create unique index if not exists next_auth_sessions_token_idx on next_auth.sessions ("sessionToken");

create table if not exists next_auth.verification_tokens (
  id         bigint generated by default as identity,
  identifier text,
  token      text,
  expires    timestamptz,
  primary key (id)
);

alter table next_auth.verification_tokens enable row level security;

-- Auth.js가 JWT에서 userId를 읽기 위한 헬퍼 함수
create or replace function next_auth.uid()
returns uuid language sql stable as $$
  select coalesce(
    nullif(current_setting('request.jwt.claim.sub', true), ''),
    (nullif(current_setting('request.jwt.claims', true), '')::jsonb->>'sub')
  )::uuid
$$;
